name: Run Playwright E2E tests

on:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
      ASPNETCORE_ENVIRONMENT: CI

    steps:
      - name: Checkout test code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
