name: Run Playwright Tests
on:
  repository_dispatch:
    types: [run-e2e-tests, run-api-tests]

jobs:
  e2e:
    if: github.event.action == 'run-e2e-tests'
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
      ASPNETCORE_ENVIRONMENT: CI
    steps:
      - name: Checkout test code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright E2E tests
        run: npx playwright test tests/fake_info_frontend.spec.ts
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: playwright-report/
          retention-days: 30

  api-tests:
    if: github.event.action == 'run-api-tests'
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
      ASPNETCORE_ENVIRONMENT: CI
    steps:
      - name: Checkout test code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright API tests
        run: npx playwright test tests/api.spec.ts
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: playwright-report/
          retention-days: 30


